version: "3.9"

services:
  chatbot:
    build:
      context: ./chatbot_pytorch_linux
      dockerfile: ../Dockerfile
      x-bake:
        tags:
        - ${DOCKER_IMAGE}
        - ${DOCKER_IMAGE_CACHE}
        - ${DOCKER_IMAGE_LATEST}
        cache_from:
        - ${DOCKER_IMAGE_CACHE}
        cache_to:
        - ${DOCKER_IMAGE_CACHE}
        output: type=registry
        push: true
        pull: true
      args:
        PY_V: ${PY_V}
        _USER: ${CB_USER}
        _GROUP: ${CB_GROUP}
        UID: ${UID}
        GID: ${GID}
        WORKDIR: ${CB_WORKDIR}